---
- name: pre-flight - Load CentOS system with EPEL Repo
  yum: 
    name: "{{ packages }}"
  vars:
    packages:
    - epel-release
    state: forcereinstall
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: pre-flight - Load CentOS system with python packages for ScoutSuite
  yum: 
    name: "{{ packages }}"
  vars:
    packages:
    - python
    - python-pip
    - python34
    - python34-pip
    - libselinux-python
    state: forcereinstall
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: pre-flight - Load Ubuntu system with python packages for ScoutSuite
  apt: 
    name: "{{ packages }}"
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - python
    - python-pip
    - python34
    - python34-pip
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: pre-flight - upgrading pip because thats what you do
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip

- name: pre-flight - Install pip requirements.txt
  pip: 
    name: "{{ packages }}"
    executable: pip3
  vars:
    packages:
    - python-dateutil>=2.2
    - netaddr>=0.7.11
    - boto3>=1.9.60
    - opinel>=3.3.4
    - pyyaml>=3.12
    - scoutsuite

#- name: pre-flight - Load system with ScoutSuite
#  pip: 
#    name: "{{ packages }}"
#  vars:
#    packages:
#    - scoutsuite
#  executable: pip

- name: Create Holding Directory for ScoutSuite data
  file:
      path: /home/{{ ansible_ssh_user }}/ScoutSuite-Reports
      state: directory
      owner: "{{ ansible_ssh_user }}"
      group: "{{ ansible_ssh_user }}"
      mode: 0775
